---
ansible_host: 172.16.31.3

network_input_policy: ACCEPT

network_hostname: sneakyserv

network_static_dns_resolvers:
  - 172.16.31.1

network_static_routes:
  - to: default
    via: 172.16.31.1

network_static_interfaces:
  - name: eno1
    type: trunk
  - name: mgmt0
    type: vlan
    parent: eno1
    id: 30
    addrs:
      - 172.16.31.3/24
  - name: lan0
    parent: eno1
    type: vlan
    id: 10
    addrs:
      - 10.0.0.2/20
  - name: trust0
    parent: eno1
    type: vlan
    id: 15
    addrs:
      - 10.1.0.2/20

nomad_volumes:
  - name: pitman_redis
    path: /nomad/pitman_redis
    read_only: false
  - name: filespace_cfg
    path: /nomad/filespace_cfg
    read_only: false
  - name: filespace_data
    path: /nomad/filespace_data
    read_only: false
  - name: prometheus_data
    path: /nomad/prometheus
    read_only: false
  - name: grafana_data
    path: /nomad/grafana
    read_only: false

cni_networks:
  - name: trust
    parent: trust0
  - name: lan
    parent: lan0
