---
xbps_repository_address: repo-fastly.voidlinux.org
xbps_repository_main: "https://{{ xbps_repository_address }}/current/musl"
xbps_repository_nonfree: "{{xbps_repository_main }}/nonfree"
xbps_repository_port: 443
