---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - ssh_keys
    - xbps-repoconf
    - void.network.dns
    - mmc_drivers
    - chrony

- hosts: static_net
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - void.network.static
